# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0003_savedmap_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2018, 9, 12)),
            preserve_default=False,
        ),
    ]
