# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0004_savedmap_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
