# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0006_savedmap_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmap',
            name='gallery_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
