# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0007_savedmap_addindex_gallery_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='stations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
