# Generated by Django 2.1.7 on 2019-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0008_savedmap_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='naming_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
