# Generated by Django 2.1.7 on 2019-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0010_auto_20190223_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='station_count',
            field=models.IntegerField(default=-1),
        ),
    ]
