# Generated by Django 2.1.7 on 2020-01-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0012_auto_20191230_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='publicly_visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
