# Generated by Django 2.1.7 on 2020-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0013_savedmap_publicly_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='suggested_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
