# Generated by Django 2.1.7 on 2020-02-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0014_savedmap_suggested_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='suggested_city_overlap',
            field=models.IntegerField(default=-1),
        ),
    ]
