# Generated by Django 5.0.1 on 2024-01-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0016_auto_20201122_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
