# Generated by Django 5.0.1 on 2024-01-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0017_alter_savedmap_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
