# Generated by Django 5.0.1 on 2024-01-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0018_alter_savedmap_id'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmap',
            name='gallery_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='publicly_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='urlhash',
            field=models.CharField(max_length=8),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['urlhash'], name='map_saver_s_urlhash_355755_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['gallery_visible'], name='map_saver_s_gallery_399e28_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['publicly_visible'], name='map_saver_s_publicl_170e96_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['created_at'], name='map_saver_s_created_42250c_idx'),
        ),
    ]
