# Generated by Django 5.0.1 on 2024-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0019_alter_savedmap_gallery_visible_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['station_count'], name='map_saver_s_station_087683_idx'),
        ),
    ]
