# Generated by Django 5.0.1 on 2024-01-27 20:05

import map_saver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0021_savedmap_thumbnail_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='thumbnail_png',
            field=models.FileField(null=True, upload_to=map_saver.models.get_thumbnail_filepath),
        ),
    ]
