# Generated by Django 5.0.1 on 2024-01-28 17:25

import map_saver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0022_savedmap_thumbnail_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='png',
            field=models.FileField(null=True, upload_to=map_saver.models.get_image_filepath),
        ),
        migrations.AddField(
            model_name='savedmap',
            name='svg',
            field=models.FileField(null=True, upload_to=map_saver.models.get_image_filepath),
        ),
    ]
