# Generated by Django 5.0.1 on 2024-02-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0023_savedmap_png_savedmap_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
