# Generated by Django 5.0.1 on 2024-02-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0024_savedmap_data'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmap',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedmap',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['likes'], name='map_saver_s_likes_a61eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['dislikes'], name='map_saver_s_dislike_43db27_idx'),
        ),
    ]
