# Generated by Django 5.0.1 on 2024-03-19 02:46

import map_saver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0025_savedmap_dislikes_savedmap_likes_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmap',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='mapdata',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='png',
            field=models.FileField(blank=True, null=True, upload_to=map_saver.models.get_image_filepath),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to=map_saver.models.get_image_filepath),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='thumbnail_png',
            field=models.FileField(blank=True, null=True, upload_to=map_saver.models.get_thumbnail_filepath),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='thumbnail_svg',
            field=models.FileField(blank=True, null=True, upload_to=map_saver.models.get_thumbnail_filepath),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['svg'], name='map_saver_s_svg_2a77c2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['png'], name='map_saver_s_png_6ddb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['thumbnail_svg'], name='map_saver_s_thumbna_95e066_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['thumbnail_png'], name='map_saver_s_thumbna_2e67a3_idx'),
        ),
    ]
