# Generated by Django 5.0.1 on 2024-03-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0026_alter_savedmap_data_alter_savedmap_mapdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('map_type', models.CharField(blank=True, choices=[('real', 'This is a real map of a real transit system'), ('fantasy', 'This is a fantasy map of a real city/transit system'), ('imaginary', 'This is an imaginary place')], max_length=64, null=True)),
                ('saved_map', models.ForeignKey(help_text='Which map this identification belongs to', on_delete=django.db.models.deletion.CASCADE, to='map_saver.savedmap')),
            ],
        ),
    ]
