# Generated by Django 5.0.1 on 2024-04-30 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0028_savedmap_map_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='name',
            field=models.CharField(blank=True, default='', help_text='User-provided (or admin-provided) name for a map. When user-provided, contains tags like (real).', max_length=255),
        ),
        migrations.AlterField(
            model_name='savedmap',
            name='suggested_city',
            field=models.CharField(blank=True, default='', help_text='Suggested name for this map based on station name overlap with real, existing Metro systems.', max_length=255),
        ),
        migrations.AddField(
            model_name='savedmap',
            name='city',
            field=models.ForeignKey(blank=True, help_text='The city (location) this map refers to. Differs from name and suggested_city by being the standard, canonical name of a city.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_saver.city'),
        ),
    ]
