# Generated by Django 5.0.1 on 2024-05-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_saver', '0029_city_alter_savedmap_name_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savedmap',
            index=models.Index(fields=['suggested_city'], name='map_saver_s_suggest_44df94_idx'),
        ),
    ]
