# Generated by Django 2.1.7 on 2019-12-31 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_saver', '0012_auto_20191230_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('action', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('savedmap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_saver.SavedMap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
