# Generated by Django 2.1.7 on 2019-12-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
