CITIES = (
    'Melbourne',
    'Stepford County',
    'Toronto',
    'Washington',
    'Hong Kong',
    'London',
    'New York',
    'Boston',
    'Sydney',
    'Los Angeles',
    'Vancouver',
    'San Francisco',
    'Chicago',
    'Singapore',
    'Philadelphia',
    'São Paulo',
    'Atlanta',
    'Ostrów Mazow',
    'North America',
    'Minecraft',
    'Budapest',
    'Perth',
    'Dublin',
    'Moscow',
    'Seoul',
    'Europe',
    'Baltimore',
    'Mexico City',
    'Taipei',
    'Lisbon',
    'Calgary',
    'Warsaw',
    'Montréal', # TODO: This shows a different set of maps than Montreal
    'Rome',
    'Manila',
    'Rio de Janeiro',
    'Pintao',
    'Pittsburgh',
    'Orlando',
    'Indianapolis',
    'Stockholm',
    'Ottawa',
    'Santiago',
    'Earth',
    'Tokyo',
    'Miami',
    'Glasgow',
    'Pensenloh',
    'Amsterdam',
    'Kansas City',
    'Prague',
    'Detroit',
    'Beijing',
    'Milan',
    'Evola City',
    'Copenhagen',
    'Island of Sodor',
    'Auckland',
    'Phoenix',
    'Paris',
    'Tyne and Wear',
    'Edinburgh',
    'San Diego',
    'Las Vegas',
    'Madrid',
    'Mitteldeutsc',
    'Victoria',
    'Hanoi',
    'Seattle',
    'Buffalo',
    'Cincinnati',
    'Cambridge',
    'Richmond',
    'Edmonton',
    'PATH',
    'Jakarta',
    'Cities Skylines',
    'Frattamaggio',
    'Manila',
    'Salt Lake City',
    'Maryland',
    'Helsinki',
    'Kuala Lumpur',
    'Maverick County',
    'Hyrule',
    'Athens',
    'Forestown',
    'Hampton Road',
    'Minneapolis',
    'Bucharest',
    'Brighton',
    'California',
    'Long Island',
    'Sousse',
    'Bristol',
    'Metropolitan',
    'Vienna',
    'Columbus',
    'Austin',
    'Nusitarï',
    'Raleigh',
    'Sofia',
    'Berlin',
    'Barcelona',
    'Portland',
    'Houston',
    'Leipzig',
    'Shanghai',
    'Hartford',
    'Orange County',
    'Birmingham',
    'Istanbul',
    'Bologna',
    'Bangkok',
    'Cleveland',
    'Adelaide',
    'Belgie',
    'Cambinez',
    'Brisbane',
    'Liverpool',
    'New Zealand',
    'Hamburg',
    'Ankara',
    'Kolkata',
    'Valencia',
    'Shenzhen',
    'Mumbai',
    'Delhi',
    'Cairo',
    'Dhaka',
    'Osaka',
    'Karachi',
    'Buenos Aires',
    'Chongqing',
    'Lagos',
    'Tianjin',
    'Kinshasa',
    'Guangzhou',
    'Lahore',
    'Bangalore',
    'Bogotá',
    'Chennai',
    'Lima',
    'Nagoya',
    'Hyderabad',
    'Tehran',
    'Chengdu',
    'Nanjing',
    'Wuhan',
    'Ho Chi Minh',
    'Luanda',
    'Ahmedabad',
    'Dongguan',
    'Hangzhou',
    'Foshan',
    'Shenyang',
    'Riyadh',
    'Baghdad',
    'Surat',
    'Suzhou',
    'Pune',
    'Harbin',
    'Dallas',
    'Dar es Salaam',
    'Belo Horizonte',
    'Fukuoka',
    'Khartoum',
    'Johannesburg',
    'St Petersburg',
    'Qingdao',
    'Dalian',
    'Yangon',
    'Alexandria',
    'Jinan',
    'Guadalajara',
    'Kraków',
    'Poznań',
    'Cologne',
)
