# Generated by Django 5.0.1 on 2024-01-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapsByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('maps', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='mapsbyday',
            constraint=models.UniqueConstraint(fields=('day',), name='unique_mapsbyday_day'),
        ),
    ]
