# Generated by Django 5.0.1 on 2024-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_mapsbycity_mapsbycity_unique_mapsbycity_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsbycity',
            name='maps',
            field=models.IntegerField(null=True),
        ),
    ]
